# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/nicolasnicolaou/Documents/workspace/AtomicSharedMemory

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/nicolasnicolaou/Documents/workspace/AtomicSharedMemory

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/nicolasnicolaou/Documents/workspace/AtomicSharedMemory/CMakeFiles /Users/nicolasnicolaou/Documents/workspace/AtomicSharedMemory/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/nicolasnicolaou/Documents/workspace/AtomicSharedMemory/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named asm

# Build rule for target.
asm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 asm
.PHONY : asm

# fast build rule for target.
asm/fast:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/build
.PHONY : asm/fast

Proto-ABD/ABDRWClient.o: Proto-ABD/ABDRWClient.cpp.o

.PHONY : Proto-ABD/ABDRWClient.o

# target to build an object file
Proto-ABD/ABDRWClient.cpp.o:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/Proto-ABD/ABDRWClient.cpp.o
.PHONY : Proto-ABD/ABDRWClient.cpp.o

Proto-ABD/ABDRWClient.i: Proto-ABD/ABDRWClient.cpp.i

.PHONY : Proto-ABD/ABDRWClient.i

# target to preprocess a source file
Proto-ABD/ABDRWClient.cpp.i:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/Proto-ABD/ABDRWClient.cpp.i
.PHONY : Proto-ABD/ABDRWClient.cpp.i

Proto-ABD/ABDRWClient.s: Proto-ABD/ABDRWClient.cpp.s

.PHONY : Proto-ABD/ABDRWClient.s

# target to generate assembly for a file
Proto-ABD/ABDRWClient.cpp.s:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/Proto-ABD/ABDRWClient.cpp.s
.PHONY : Proto-ABD/ABDRWClient.cpp.s

Proto-ABD/ABDServer.o: Proto-ABD/ABDServer.cpp.o

.PHONY : Proto-ABD/ABDServer.o

# target to build an object file
Proto-ABD/ABDServer.cpp.o:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/Proto-ABD/ABDServer.cpp.o
.PHONY : Proto-ABD/ABDServer.cpp.o

Proto-ABD/ABDServer.i: Proto-ABD/ABDServer.cpp.i

.PHONY : Proto-ABD/ABDServer.i

# target to preprocess a source file
Proto-ABD/ABDServer.cpp.i:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/Proto-ABD/ABDServer.cpp.i
.PHONY : Proto-ABD/ABDServer.cpp.i

Proto-ABD/ABDServer.s: Proto-ABD/ABDServer.cpp.s

.PHONY : Proto-ABD/ABDServer.s

# target to generate assembly for a file
Proto-ABD/ABDServer.cpp.s:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/Proto-ABD/ABDServer.cpp.s
.PHONY : Proto-ABD/ABDServer.cpp.s

Proto-ABD/ABD_protocol.o: Proto-ABD/ABD_protocol.cpp.o

.PHONY : Proto-ABD/ABD_protocol.o

# target to build an object file
Proto-ABD/ABD_protocol.cpp.o:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/Proto-ABD/ABD_protocol.cpp.o
.PHONY : Proto-ABD/ABD_protocol.cpp.o

Proto-ABD/ABD_protocol.i: Proto-ABD/ABD_protocol.cpp.i

.PHONY : Proto-ABD/ABD_protocol.i

# target to preprocess a source file
Proto-ABD/ABD_protocol.cpp.i:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/Proto-ABD/ABD_protocol.cpp.i
.PHONY : Proto-ABD/ABD_protocol.cpp.i

Proto-ABD/ABD_protocol.s: Proto-ABD/ABD_protocol.cpp.s

.PHONY : Proto-ABD/ABD_protocol.s

# target to generate assembly for a file
Proto-ABD/ABD_protocol.cpp.s:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/Proto-ABD/ABD_protocol.cpp.s
.PHONY : Proto-ABD/ABD_protocol.cpp.s

Server/arguments.o: Server/arguments.cpp.o

.PHONY : Server/arguments.o

# target to build an object file
Server/arguments.cpp.o:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/Server/arguments.cpp.o
.PHONY : Server/arguments.cpp.o

Server/arguments.i: Server/arguments.cpp.i

.PHONY : Server/arguments.i

# target to preprocess a source file
Server/arguments.cpp.i:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/Server/arguments.cpp.i
.PHONY : Server/arguments.cpp.i

Server/arguments.s: Server/arguments.cpp.s

.PHONY : Server/arguments.s

# target to generate assembly for a file
Server/arguments.cpp.s:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/Server/arguments.cpp.s
.PHONY : Server/arguments.cpp.s

Server/filesystem.o: Server/filesystem.cpp.o

.PHONY : Server/filesystem.o

# target to build an object file
Server/filesystem.cpp.o:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/Server/filesystem.cpp.o
.PHONY : Server/filesystem.cpp.o

Server/filesystem.i: Server/filesystem.cpp.i

.PHONY : Server/filesystem.i

# target to preprocess a source file
Server/filesystem.cpp.i:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/Server/filesystem.cpp.i
.PHONY : Server/filesystem.cpp.i

Server/filesystem.s: Server/filesystem.cpp.s

.PHONY : Server/filesystem.s

# target to generate assembly for a file
Server/filesystem.cpp.s:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/Server/filesystem.cpp.s
.PHONY : Server/filesystem.cpp.s

Server/set_operations.o: Server/set_operations.cpp.o

.PHONY : Server/set_operations.o

# target to build an object file
Server/set_operations.cpp.o:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/Server/set_operations.cpp.o
.PHONY : Server/set_operations.cpp.o

Server/set_operations.i: Server/set_operations.cpp.i

.PHONY : Server/set_operations.i

# target to preprocess a source file
Server/set_operations.cpp.i:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/Server/set_operations.cpp.i
.PHONY : Server/set_operations.cpp.i

Server/set_operations.s: Server/set_operations.cpp.s

.PHONY : Server/set_operations.s

# target to generate assembly for a file
Server/set_operations.cpp.s:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/Server/set_operations.cpp.s
.PHONY : Server/set_operations.cpp.s

Server/sm_common.o: Server/sm_common.cpp.o

.PHONY : Server/sm_common.o

# target to build an object file
Server/sm_common.cpp.o:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/Server/sm_common.cpp.o
.PHONY : Server/sm_common.cpp.o

Server/sm_common.i: Server/sm_common.cpp.i

.PHONY : Server/sm_common.i

# target to preprocess a source file
Server/sm_common.cpp.i:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/Server/sm_common.cpp.i
.PHONY : Server/sm_common.cpp.i

Server/sm_common.s: Server/sm_common.cpp.s

.PHONY : Server/sm_common.s

# target to generate assembly for a file
Server/sm_common.cpp.s:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/Server/sm_common.cpp.s
.PHONY : Server/sm_common.cpp.s

Server/sm_node.o: Server/sm_node.cpp.o

.PHONY : Server/sm_node.o

# target to build an object file
Server/sm_node.cpp.o:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/Server/sm_node.cpp.o
.PHONY : Server/sm_node.cpp.o

Server/sm_node.i: Server/sm_node.cpp.i

.PHONY : Server/sm_node.i

# target to preprocess a source file
Server/sm_node.cpp.i:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/Server/sm_node.cpp.i
.PHONY : Server/sm_node.cpp.i

Server/sm_node.s: Server/sm_node.cpp.s

.PHONY : Server/sm_node.s

# target to generate assembly for a file
Server/sm_node.cpp.s:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/Server/sm_node.cpp.s
.PHONY : Server/sm_node.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... asm"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Proto-ABD/ABDRWClient.o"
	@echo "... Proto-ABD/ABDRWClient.i"
	@echo "... Proto-ABD/ABDRWClient.s"
	@echo "... Proto-ABD/ABDServer.o"
	@echo "... Proto-ABD/ABDServer.i"
	@echo "... Proto-ABD/ABDServer.s"
	@echo "... Proto-ABD/ABD_protocol.o"
	@echo "... Proto-ABD/ABD_protocol.i"
	@echo "... Proto-ABD/ABD_protocol.s"
	@echo "... Server/arguments.o"
	@echo "... Server/arguments.i"
	@echo "... Server/arguments.s"
	@echo "... Server/filesystem.o"
	@echo "... Server/filesystem.i"
	@echo "... Server/filesystem.s"
	@echo "... Server/set_operations.o"
	@echo "... Server/set_operations.i"
	@echo "... Server/set_operations.s"
	@echo "... Server/sm_common.o"
	@echo "... Server/sm_common.i"
	@echo "... Server/sm_common.s"
	@echo "... Server/sm_node.o"
	@echo "... Server/sm_node.i"
	@echo "... Server/sm_node.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

