# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/nicolasnicolaou/Documents/workspace/ATOMICEmulator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/nicolasnicolaou/Documents/workspace/ATOMICEmulator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/nicolasnicolaou/Documents/workspace/ATOMICEmulator/CMakeFiles /Users/nicolasnicolaou/Documents/workspace/ATOMICEmulator/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/nicolasnicolaou/Documents/workspace/ATOMICEmulator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named asm

# Build rule for target.
asm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 asm
.PHONY : asm

# fast build rule for target.
asm/fast:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/build
.PHONY : asm/fast

Protocols/ABD/abd_client.o: Protocols/ABD/abd_client.cpp.o

.PHONY : Protocols/ABD/abd_client.o

# target to build an object file
Protocols/ABD/abd_client.cpp.o:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/Protocols/ABD/abd_client.cpp.o
.PHONY : Protocols/ABD/abd_client.cpp.o

Protocols/ABD/abd_client.i: Protocols/ABD/abd_client.cpp.i

.PHONY : Protocols/ABD/abd_client.i

# target to preprocess a source file
Protocols/ABD/abd_client.cpp.i:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/Protocols/ABD/abd_client.cpp.i
.PHONY : Protocols/ABD/abd_client.cpp.i

Protocols/ABD/abd_client.s: Protocols/ABD/abd_client.cpp.s

.PHONY : Protocols/ABD/abd_client.s

# target to generate assembly for a file
Protocols/ABD/abd_client.cpp.s:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/Protocols/ABD/abd_client.cpp.s
.PHONY : Protocols/ABD/abd_client.cpp.s

Protocols/ABD/abd_server.o: Protocols/ABD/abd_server.cpp.o

.PHONY : Protocols/ABD/abd_server.o

# target to build an object file
Protocols/ABD/abd_server.cpp.o:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/Protocols/ABD/abd_server.cpp.o
.PHONY : Protocols/ABD/abd_server.cpp.o

Protocols/ABD/abd_server.i: Protocols/ABD/abd_server.cpp.i

.PHONY : Protocols/ABD/abd_server.i

# target to preprocess a source file
Protocols/ABD/abd_server.cpp.i:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/Protocols/ABD/abd_server.cpp.i
.PHONY : Protocols/ABD/abd_server.cpp.i

Protocols/ABD/abd_server.s: Protocols/ABD/abd_server.cpp.s

.PHONY : Protocols/ABD/abd_server.s

# target to generate assembly for a file
Protocols/ABD/abd_server.cpp.s:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/Protocols/ABD/abd_server.cpp.s
.PHONY : Protocols/ABD/abd_server.cpp.s

Protocols/sm_protocol.o: Protocols/sm_protocol.cpp.o

.PHONY : Protocols/sm_protocol.o

# target to build an object file
Protocols/sm_protocol.cpp.o:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/Protocols/sm_protocol.cpp.o
.PHONY : Protocols/sm_protocol.cpp.o

Protocols/sm_protocol.i: Protocols/sm_protocol.cpp.i

.PHONY : Protocols/sm_protocol.i

# target to preprocess a source file
Protocols/sm_protocol.cpp.i:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/Protocols/sm_protocol.cpp.i
.PHONY : Protocols/sm_protocol.cpp.i

Protocols/sm_protocol.s: Protocols/sm_protocol.cpp.s

.PHONY : Protocols/sm_protocol.s

# target to generate assembly for a file
Protocols/sm_protocol.cpp.s:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/Protocols/sm_protocol.cpp.s
.PHONY : Protocols/sm_protocol.cpp.s

Utilities/arguments.o: Utilities/arguments.cpp.o

.PHONY : Utilities/arguments.o

# target to build an object file
Utilities/arguments.cpp.o:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/Utilities/arguments.cpp.o
.PHONY : Utilities/arguments.cpp.o

Utilities/arguments.i: Utilities/arguments.cpp.i

.PHONY : Utilities/arguments.i

# target to preprocess a source file
Utilities/arguments.cpp.i:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/Utilities/arguments.cpp.i
.PHONY : Utilities/arguments.cpp.i

Utilities/arguments.s: Utilities/arguments.cpp.s

.PHONY : Utilities/arguments.s

# target to generate assembly for a file
Utilities/arguments.cpp.s:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/Utilities/arguments.cpp.s
.PHONY : Utilities/arguments.cpp.s

Utilities/filesystem.o: Utilities/filesystem.cpp.o

.PHONY : Utilities/filesystem.o

# target to build an object file
Utilities/filesystem.cpp.o:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/Utilities/filesystem.cpp.o
.PHONY : Utilities/filesystem.cpp.o

Utilities/filesystem.i: Utilities/filesystem.cpp.i

.PHONY : Utilities/filesystem.i

# target to preprocess a source file
Utilities/filesystem.cpp.i:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/Utilities/filesystem.cpp.i
.PHONY : Utilities/filesystem.cpp.i

Utilities/filesystem.s: Utilities/filesystem.cpp.s

.PHONY : Utilities/filesystem.s

# target to generate assembly for a file
Utilities/filesystem.cpp.s:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/Utilities/filesystem.cpp.s
.PHONY : Utilities/filesystem.cpp.s

Utilities/set_operations.o: Utilities/set_operations.cpp.o

.PHONY : Utilities/set_operations.o

# target to build an object file
Utilities/set_operations.cpp.o:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/Utilities/set_operations.cpp.o
.PHONY : Utilities/set_operations.cpp.o

Utilities/set_operations.i: Utilities/set_operations.cpp.i

.PHONY : Utilities/set_operations.i

# target to preprocess a source file
Utilities/set_operations.cpp.i:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/Utilities/set_operations.cpp.i
.PHONY : Utilities/set_operations.cpp.i

Utilities/set_operations.s: Utilities/set_operations.cpp.s

.PHONY : Utilities/set_operations.s

# target to generate assembly for a file
Utilities/set_operations.cpp.s:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/Utilities/set_operations.cpp.s
.PHONY : Utilities/set_operations.cpp.s

Utilities/sm_common.o: Utilities/sm_common.cpp.o

.PHONY : Utilities/sm_common.o

# target to build an object file
Utilities/sm_common.cpp.o:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/Utilities/sm_common.cpp.o
.PHONY : Utilities/sm_common.cpp.o

Utilities/sm_common.i: Utilities/sm_common.cpp.i

.PHONY : Utilities/sm_common.i

# target to preprocess a source file
Utilities/sm_common.cpp.i:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/Utilities/sm_common.cpp.i
.PHONY : Utilities/sm_common.cpp.i

Utilities/sm_common.s: Utilities/sm_common.cpp.s

.PHONY : Utilities/sm_common.s

# target to generate assembly for a file
Utilities/sm_common.cpp.s:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/Utilities/sm_common.cpp.s
.PHONY : Utilities/sm_common.cpp.s

Utilities/sm_node.o: Utilities/sm_node.cpp.o

.PHONY : Utilities/sm_node.o

# target to build an object file
Utilities/sm_node.cpp.o:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/Utilities/sm_node.cpp.o
.PHONY : Utilities/sm_node.cpp.o

Utilities/sm_node.i: Utilities/sm_node.cpp.i

.PHONY : Utilities/sm_node.i

# target to preprocess a source file
Utilities/sm_node.cpp.i:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/Utilities/sm_node.cpp.i
.PHONY : Utilities/sm_node.cpp.i

Utilities/sm_node.s: Utilities/sm_node.cpp.s

.PHONY : Utilities/sm_node.s

# target to generate assembly for a file
Utilities/sm_node.cpp.s:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/Utilities/sm_node.cpp.s
.PHONY : Utilities/sm_node.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... asm"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Protocols/ABD/abd_client.o"
	@echo "... Protocols/ABD/abd_client.i"
	@echo "... Protocols/ABD/abd_client.s"
	@echo "... Protocols/ABD/abd_server.o"
	@echo "... Protocols/ABD/abd_server.i"
	@echo "... Protocols/ABD/abd_server.s"
	@echo "... Protocols/sm_protocol.o"
	@echo "... Protocols/sm_protocol.i"
	@echo "... Protocols/sm_protocol.s"
	@echo "... Utilities/arguments.o"
	@echo "... Utilities/arguments.i"
	@echo "... Utilities/arguments.s"
	@echo "... Utilities/filesystem.o"
	@echo "... Utilities/filesystem.i"
	@echo "... Utilities/filesystem.s"
	@echo "... Utilities/set_operations.o"
	@echo "... Utilities/set_operations.i"
	@echo "... Utilities/set_operations.s"
	@echo "... Utilities/sm_common.o"
	@echo "... Utilities/sm_common.i"
	@echo "... Utilities/sm_common.s"
	@echo "... Utilities/sm_node.o"
	@echo "... Utilities/sm_node.i"
	@echo "... Utilities/sm_node.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

